# Generated by Django 4.0.4 on 2022-05-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statii', '0002_statie_statieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statie',
            name='StatieID',
            field=models.IntegerField(),
        ),
    ]
