# Generated by Django 4.0.4 on 2022-07-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statii', '0003_alter_statie_statieid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autobuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('idBus', models.IntegerField()),
                ('nrInm', models.CharField(max_length=255)),
            ],
        ),
    ]
